### ISSUE TITLE
Getting NotFoundHttpException  at First hit

### ISSUE THREAD

**Issue by rrajesh145** [todstoychev/Laravel5Starter#21]
Hi. 
I have followed the steps which is given in readme file. all the commands are completed and when i tried to get into first page getting below error : 

NotFoundHttpException in Controller.php line 269:
Controller method not found.
in Controller.php line 269
at Controller->missingMethod(array('laravel'))
at call_user_func_array(array(object(IndexController), 'missingMethod'), array('_missing' => array('laravel'))) in Controller.php line 256

URL  : http://localhost/laravel/
Can anyone please suggest me , if i am missing anything

**Comment by todstoychev** [comment]
I will try tomorrow to reproduce your problem. And I will give you an explanation. On a first sight it seems like a problem with the directory structure and the server configuration. It seems like it is looking for a method getLaravel() in the index controller. Check your directory structure or try to change the .htaccess files. I am sure that the documentation is right but I will try to reproduce it. You know we are humans and we make mistakes. Thanx for the response.

**Comment by todstoychev** [comment]
Also I will got implement the missingMethod() thats why this exception is raised. Your issue is a good reason to do it. And maybe I will make a new release tomorrow.

**Comment by rrajesh145** [comment]
Thanks for quick response,  As you already wrote some rules in .htaccess file , i have not changed it , If you suggesting to change or any dir structure , let me know i will change accordingly . Or else i need to wait for new release ?

**Comment by todstoychev** [comment]
I did not have much time today but I will try to add this missingMethod() as soon as possible. If try to access the http://localhost I think you should be able to access the home page. It also tricky part with the ACL. If you miss to run php artisan acl:update you will be not able access the project. But I think that the reason for the error is not this. Can you describe me your directory structure or attach a screenshot of the web root directory. You should have something like:
www/
       |-laravel
       |-some_other_project

Where www is the webroot.

**Comment by rrajesh145** [comment]
Yes I can run when i use php artisan serve command (i.e ) http://localhost:8000/,  but now with normal url http://localhost/laravel i am facing the isse. I use below dir structure . 
Note : If have not missed to run php artisan acl:update 

htdocs/
|-laravel
|-some_other_projec

And one more issue noticed i noticed is getting below error while registering . But user can login even-though mail has not sent and without mail confirmation. 

"stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed"

**Comment by todstoychev** [comment]
I fixed the problem with user account confirmation. Now it works as expected. 
The last error that you send me is caused by some certificate problem. I think [this](https://www.google.bg/search?client=ubuntu&channel=fs&q=stream_socket_enable_crypto%28%29%3A+SSL+operation+failed+with+code+1.+OpenSSL+Error+messages%3A+error%3A14090086%3ASSL+routines%3ASSL3_GET_SERVER_CERTIFICATE%3Acertificate+verify+failed&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=AKltVouhK7Oz8weJo7-4Dw) will help you solve the issue. 
Your initial problem with the missing method exception is caused by Apache configuration. Do you have mod_rewrite enabled?

**Comment by todstoychev** [comment]
New release added which adds the missingMethod().
