### ISSUE TITLE
avatar

### ISSUE THREAD

**Issue by jespersgaard** [todstoychev/Laravel5Starter#24]
hello, nice script, just started to play around.
when i try and add avatar i get this error:

Whoops, looks like something went wrong.

1/1
FatalErrorException in Processor.php line 6:
Cannot use Todstoychev\Icr as Icr because the name is already in use

any suggestions?

regards Martin

**Comment by todstoychev** [comment]
Thanx for the response.  

Will try to fix this in the weekend. I think that it is a simple issue.
Duplicated namespace probably.

**Comment by todstoychev** [comment]
Try to run `composer update` it should fix the things. It seems that you are using old version of Todstoychev\Icr.
