### ISSUE TITLE
Searching for permissions results in a 404

### ISSUE THREAD

**Issue by losttheplot** [todstoychev/Laravel5Starter#29]
resources/views/admin/permissions/all.blade.php line 11 is missing the path locale:

```
<form action="{{ url($uri . '/search') }}" method="POST" class="navbar-form pull-right" role="search">
should be:
<form action="{{ url(\Illuminate\Support\Facades\App::getLocale() . '/' . $uri . '/search') }}" method="POST" class="navbar-form pull-right" role="search">
```

**Comment by todstoychev** [comment]
Release v0.9.2 should fix the error. Keep in mind that your application should have rights to read and write in the `storage/app/lucene-search`. Sometimes this gets me trouble.
