### ISSUE TITLE
The localhost page isn’t working. Localhost redirected you too many times.

### ISSUE THREAD

**Issue by MJunaidAhmad** [todstoychev/Laravel5Starter#33]
The whole project was working very well until i added a new role ("test") and then added a new user ("junaid") then assigned the new role ("test") to this new user ("junaid") and then logged in.
After logging with this new user I got this error.
![issue](https://cloud.githubusercontent.com/assets/12229238/16481180/3fe36e34-3ec3-11e6-9831-572fe33007dc.PNG).

It seems like when i logged in with this new user ("junaid"), it directed me to the ("/") page and then
it redirected me back, hence an infinite loop.
Another important point is that when i created this new role ("test") then in the 'role' table it's id=3. When I checked the 'permissions' table where ever 'role_id' must be equal to 3, it was null.
It means the user with this role was not permitted to any access any page (in other words.)
Here is the screenshot of 'permissions' table.

![role](https://cloud.githubusercontent.com/assets/12229238/16482256/63b7dade-3ec8-11e6-9647-4b454c6e6a41.PNG)

Kindly let me know if i am missing something.

Regards,
Junaid Ahmad

**Comment by MJunaidAhmad** [comment]
Okay I replaced all the null values (for 'role_id' in the 'permissions' table) and now ,it is working fine. But please let me know where is the problem in the code as I am also debugging it.

**Comment by MJunaidAhmad** [comment]
okay it has been resolved by running the php artisan acl:clear command.

**Comment by todstoychev** [comment]
You can use acl:update also.

via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.4.40&pv=4.4.4&source=email_footer_2] On Thu, Jun 30, 2016 at 1:15 PM, Junaid Ahmad < notifications@github.com [notifications@github.com] > wrote:
okay it has been resolved by running the php artisan acl:clear command.

**Comment by MJunaidAhmad** [comment]
Exactly.

Thanks for replying. :)
